version: '3.3'

services:

    postgres:
      image: postgres
      restart: always
      ports:
        - "5433:5432"

      environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_local

    pgadmin:
      image: dpage/pgadmin4

      environment:
        PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
      - "8080:80" 
      depends_on:
      - postgres
      